### ISSUE TITLE
Créer une page qui indique le matériel en cours de réservation, en cours d’emprunt, non cloturé.

### ISSUE THREAD

**Issue by Bvr4** [Bvr4/gestion-emprunt-et-reservation-materiel#4]

**Comment by NicolasMenegale** [comment]
Propositions :

1. Créer une méthode qui retourne l'état du matériel dans le modèle matériel (un peu comme has_emprunts_encours sur utilisateur)
2. Refaire la vue index d'affichage pour afficher la liste des matériel et appeler la méthode pour l'état du matériel (créé précédemment) dans le template
3. Mettre des django_filters sur l'état pour pouvoir sélectionner celui-ci et trier en fonction de l'état

**Comment by Bvr4** [comment]
Il reste à faire un peu de mise en page, et jouer avec HTMX pour rendre tout ça plus dynamique.
